Add participants
PavelProjects/organizer pull request #17
Opened 2022-11-06 18:38 UTC by vlolad

2022-11-06 19:49 UTC, PavelProjects requested changes
в целом норм, валидацию прикольно реализовал

2022-11-06 19:49 UTC, PavelProjects commented on db_rollout.sql
> +insert into dict_task_status (name, caption) values ('new', 'New'), ('doing', 'In progress'), ('done', 'Complete');
doing? doing бл? :D
замени:
doing -> execution
done -> finished

2022-11-06 19:49 UTC, PavelProjects commented on src/main/java/com/povobolapo/organizer/controller/TaskController.java
> +        return taskMapper.toDto(taskService.create(taskMapper.toEntity(task), task.getParticipants()));
не проще переписать метод create и прокидывать туда сразу TaskRequestBody task?

2022-11-06 19:49 UTC, PavelProjects commented on src/main/java/com/povobolapo/organizer/controller/model/task/TaskRequestBody.java
> +    @NotNull(groups = OnCreate.class)
а что это?

2022-11-06 20:44 UTC, vlolad commented on db_rollout.sql
> +insert into dict_task_status (name, caption) values ('new', 'New'), ('doing', 'In progress'), ('done', 'Complete');
Ето же стоковые названия столбцов в notion(((

2022-11-06 20:45 UTC, vlolad commented on src/main/java/com/povobolapo/organizer/controller/model/task/TaskRequestBody.java
> +    @NotNull(groups = OnCreate.class)
https://vk.com/@javatutorial-validaciya-dannyh-v-spring-boot

Кастомная валидация по параметрам

2022-11-06 20:45 UTC, vlolad commented on src/main/java/com/povobolapo/organizer/controller/TaskController.java
> +        return taskMapper.toDto(taskService.create(taskMapper.toEntity(task), task.getParticipants()));
Соглы

2022-11-08 18:26 UTC, PavelProjects requested changes

2022-11-08 18:26 UTC, PavelProjects commented on db_rollout.sql
> +insert into dict_task_status (name, caption) values ('new', 'New'), ('doing', 'In progress'), ('done', 'Complete');
это даже блин не звучит 
doing who? ur mom???

2022-11-08 18:26 UTC, PavelProjects commented on src/main/java/com/povobolapo/organizer/controller/model/task/TaskSearchRequest.java
> +    private String login = null;
за что это поле отвечает?

2022-11-08 18:26 UTC, PavelProjects commented on src/main/java/com/povobolapo/organizer/model/TaskEntity.java
> +    public Iterator<UserEntity> iterator() {
а это зачем?

2022-11-08 18:26 UTC, PavelProjects commented on src/main/java/com/povobolapo/organizer/model/UserEntity.java
> +    public boolean equals(Object o) {
не очень понятно зачем

2022-11-08 18:26 UTC, PavelProjects commented on src/main/java/com/povobolapo/organizer/service/TaskService.java
> +    // @poeblo спасибо!!!!!!!!!!!!
ты забыл добавить проверку

2022-11-08 21:04 UTC, vlolad commented on src/main/java/com/povobolapo/organizer/controller/model/task/TaskSearchRequest.java
> +    private String login = null;
Поиск по автору
Да надо переименовать

2022-11-15 16:10 UTC, vlolad commented on src/main/java/com/povobolapo/organizer/model/TaskEntity.java
> +    public Iterator<UserEntity> iterator() {
no

2022-11-15 16:12 UTC, vlolad commented on src/main/java/com/povobolapo/organizer/model/UserEntity.java
> +    public boolean equals(Object o) {
Просто переопределил, чтобы сравнивать по содержимому юзера

2022-11-15 16:15 UTC, vlolad commented on src/main/java/com/povobolapo/organizer/service/TaskService.java
> +    // @poeblo спасибо!!!!!!!!!!!!
Добавил

2022-11-15 16:17 UTC, PavelProjects approved these changes

2022-11-15 16:38 UTC, PavelProjects approved these changes

2022-11-15 17:01 UTC, merged